name: newdrupal
recipe: drupal9

config:
  via: nginx
  webroot: web
  xdebug: true
  database: mysql:8.0

services:
  database:
    type: mysql:8.0
  appserver:
    xdebug: true
    type: php:8.1
    composer_version: 2-latest